name: Auto Merge Dependabot PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_METHOD: "squash"
